//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace weebumconfig {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class SettingsFile : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsFile defaultInstance = ((SettingsFile)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsFile())));
        
        public static SettingsFile Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PREVIOUS_FFMPEG_PATH {
            get {
                return ((string)(this["PREVIOUS_FFMPEG_PATH"]));
            }
            set {
                this["PREVIOUS_FFMPEG_PATH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PREVIOUS_VIDEO_FOLDER {
            get {
                return ((string)(this["PREVIOUS_VIDEO_FOLDER"]));
            }
            set {
                this["PREVIOUS_VIDEO_FOLDER"] = value;
            }
        }
    }
}
